# Site settings
title: André Onuki
email: andreonuki@acm.org
description: > # this means to ignore newlines until "baseurl:"
  This is the personal webpage of André Onuki.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meiao.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  meiao

# Build settings
markdown: kramdown
highlither: rouge
